

services:
  

  db:
    image: postgres:17
    container_name: reflex-db
    env_file:
      - ./.env
    ports:
      - 5431:5432
    volumes:
      - C:/containers/database/reflex-ads/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reflex -d reflex_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: reflex-backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"